name: Deploy Laravel

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yusnars/laravel-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/laravel-docker
            docker pull yusnars/laravel-app:latest
            docker stop laravel-app || true
            docker rm laravel-app || true
            docker run -d \
            --name laravel-app \
            -p 5000:80 \
            -v /var/www/laravel-docker/.env:/var/www/html/deploy/daarulmukhtarin/.env \
            yusnars/laravel-app:latest
            docker exec laravel-app php artisan migrate --force
            docker exec laravel-app php artisan config:clear
            docker exec laravel-app php artisan cache:clear
            docker exec laravel-app php artisan config:cache
